/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.frame;

import com.sun.glass.events.KeyEvent;

import com.query.Base_Operations;

/**
 *
 * @author suret
 */
public class EditFrame extends javax.swing.JFrame {

    Base_Operations operations = new Base_Operations();

    /**
     * Creates new form EditFrame
     */
    public EditFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edit_error = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        name_edit = new javax.swing.JTextField();
        count_edit = new javax.swing.JTextField();
        price_edit = new javax.swing.JTextField();
        icon_name = new javax.swing.JLabel();
        icon_pieces = new javax.swing.JLabel();
        icon_price = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        save_text = new javax.swing.JLabel();
        cancel_text = new javax.swing.JLabel();
        icon_category = new javax.swing.JLabel();
        category_edit = new javax.swing.JComboBox<>();
        barcode_edit = new javax.swing.JTextField();
        icon_barcode = new javax.swing.JLabel();
        description_edit = new javax.swing.JTextField();
        icon_description = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EDIT ");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(45, 138, 171));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        name_edit.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        name_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        name_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                name_editFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                name_editFocusLost(evt);
            }
        });
        name_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_editActionPerformed(evt);
            }
        });
        jPanel1.add(name_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 180, 30));

        count_edit.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        count_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        count_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                count_editFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                count_editFocusLost(evt);
            }
        });
        jPanel1.add(count_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 180, 30));

        price_edit.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        price_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        price_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                price_editFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                price_editFocusLost(evt);
            }
        });
        price_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                price_editActionPerformed(evt);
            }
        });
        price_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                price_editKeyPressed(evt);
            }
        });
        jPanel1.add(price_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 180, 30));

        icon_name.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/abc-block - edit.png"))); // NOI18N
        jPanel1.add(icon_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 30, 30));

        icon_pieces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/number - edit.png"))); // NOI18N
        jPanel1.add(icon_pieces, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        icon_price.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/coin -edit.png"))); // NOI18N
        jPanel1.add(icon_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/floppy-disk.png"))); // NOI18N
        save.setBorder(null);
        save.setBorderPainted(false);
        save.setContentAreaFilled(false);
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveMouseExited(evt);
            }
        });
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/cancel.png"))); // NOI18N
        cancel.setBorder(null);
        cancel.setContentAreaFilled(false);
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        save_text.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        save_text.setText("Save");
        jPanel1.add(save_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, -1, -1));
        save_text.setVisible(false);

        cancel_text.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        cancel_text.setText("Cancel");
        jPanel1.add(cancel_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));
        cancel_text.setVisible(false);

        icon_category.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/list - edit.png"))); // NOI18N
        jPanel1.add(icon_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 30, 30));

        category_edit.setBackground(new java.awt.Color(211, 222, 249));
        category_edit.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        category_edit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Non-food", "Drink", "General" }));
        category_edit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(221, 222, 249), 1, true));
        category_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                category_editActionPerformed(evt);
            }
        });
        category_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                category_editKeyPressed(evt);
            }
        });
        jPanel1.add(category_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 180, 30));

        barcode_edit.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        barcode_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barcode_edit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                barcode_editFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                barcode_editFocusLost(evt);
            }
        });
        barcode_edit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barcode_editKeyPressed(evt);
            }
        });
        jPanel1.add(barcode_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 180, 30));

        icon_barcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/barcode3 - edit.png"))); // NOI18N
        jPanel1.add(icon_barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        description_edit.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        description_edit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(description_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 180, 30));

        icon_description.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icons/description - edit.png"))); // NOI18N
        jPanel1.add(icon_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void name_editFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_editFocusGained
        if (name_edit.getText().trim().equals("Product's name")) {
            name_edit.setText("");
        }
    }//GEN-LAST:event_name_editFocusGained

    private void name_editFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_name_editFocusLost
        if (name_edit.getText().isEmpty()) {
            name_edit.setText("Product's name");
        }
    }//GEN-LAST:event_name_editFocusLost

    private void name_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_editActionPerformed

    private void count_editFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_count_editFocusGained
        if (count_edit.getText().trim().equals("Product's count")) {
            count_edit.setText("");
        }
    }//GEN-LAST:event_count_editFocusGained

    private void count_editFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_count_editFocusLost
        if (count_edit.getText().isEmpty()) {
            count_edit.setText("Product's count");
        }
    }//GEN-LAST:event_count_editFocusLost

    private void price_editFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_price_editFocusGained
        if (price_edit.getText().trim().equals("Product's price")) {
            price_edit.setText("");
        }
    }//GEN-LAST:event_price_editFocusGained

    private void price_editFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_price_editFocusLost
        if (price_edit.getText().isEmpty()) {
            price_edit.setText("Product's price");
        }
    }//GEN-LAST:event_price_editFocusLost

    private void price_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_price_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_price_editActionPerformed

    private void saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseEntered
        save_text.setVisible(true);
    }//GEN-LAST:event_saveMouseEntered

    private void saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseExited
        save_text.setVisible(false);
    }//GEN-LAST:event_saveMouseExited

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel_text.setVisible(true);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel_text.setVisible(false);
    }//GEN-LAST:event_cancelMouseExited

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        String name = name_edit.getText();
        String count = count_edit.getText();
        String price = price_edit.getText();
        String category = category_edit.getSelectedItem().toString();
        String barcode = barcode_edit.getText();
        String description = description_edit.getText();
        MainFrame p = new MainFrame();

        if ((name.trim().equals("Product's name")) || (count.trim().equals("Product's count")) || (price.trim().equals("Product's price")
                || (barcode.trim().equals("Product's barcode")))
                || (name.isEmpty()) || (count.isEmpty()) || (price.isEmpty()) || (barcode.isEmpty())) {
            edit_error.showMessageDialog(this, "Please check the boxes again", "Warning", edit_error.ERROR_MESSAGE);
        } else {

            int selectedRow = p.selectRow;

            int id = (int) p.model.getValueAt(selectedRow, 0);

            operations.productsUpdate(name, count, price, category, barcode, description, id);

            dispose();
           
            
        }


    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void category_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_category_editActionPerformed

    }//GEN-LAST:event_category_editActionPerformed

    private void price_editKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_price_editKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            save.doClick();
        }

    }//GEN-LAST:event_price_editKeyPressed

    private void category_editKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_category_editKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            save.doClick();
        }
    }//GEN-LAST:event_category_editKeyPressed

    private void barcode_editFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_barcode_editFocusGained
        if (barcode_edit.getText().trim().equals("Məhsulun barcode")) {
            barcode_edit.setText("");
        }
    }//GEN-LAST:event_barcode_editFocusGained

    private void barcode_editFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_barcode_editFocusLost
        if (barcode_edit.getText().isEmpty()) {
            barcode_edit.setText("Məhsulun barcode");
        }
    }//GEN-LAST:event_barcode_editFocusLost

    private void barcode_editKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcode_editKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barcode_editKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField barcode_edit;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel cancel_text;
    public javax.swing.JComboBox<String> category_edit;
    public javax.swing.JTextField count_edit;
    public javax.swing.JTextField description_edit;
    private javax.swing.JOptionPane edit_error;
    private javax.swing.JLabel icon_barcode;
    private javax.swing.JLabel icon_category;
    private javax.swing.JLabel icon_description;
    private javax.swing.JLabel icon_name;
    private javax.swing.JLabel icon_pieces;
    private javax.swing.JLabel icon_price;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField name_edit;
    public javax.swing.JTextField price_edit;
    public javax.swing.JButton save;
    private javax.swing.JLabel save_text;
    // End of variables declaration//GEN-END:variables

}
